# Stage 1: Build stage
FROM node:latest AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:alpine

WORKDIR /usr/src/app
RUN rm -rf /usr/src/app/*

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app .

EXPOSE 3000

CMD [ "node", "app.js" ]
